import type { Metadata } from "next";
import { Geist_Mono, Montserrat } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";
import Providers from "@/Providers/Providers";

const geistSans = Montserrat({
  variable: "--font-montserrat-sans",
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <Providers>
          {/* <Navbar /> */}
          <Toaster position="top-center" duration={1000} richColors />
          {children}
        </Providers>
      </body>
    </html>
  );
}
